FORMAT: 1A
HOST: http://www.google.com

# sanityapp
Sanity provides an API to control the attached scanner

## Preview [/api/preview]
### Generate a new low-resolution preview [GET]
+ Response 200 (application/json)

        [{
          "response": "ok"
        }]

## Scan Image [/api/scanimage?filename={filename}]

+ Parameters
    + filename (required, string, `important_scan.png`) ... Name of the file to scan, including file type extension.
    
### Generate a new scan [GET]
+ Response 200 (application/json)

        [{
          "response": "<file name>"
        }]

## Completed scans [/api/completed{?id=id}]

+ Parameters
    + id (optional, id, `1`) ... Numeric `id` of the scan to download. If not specified, returns the list of completed scans available.

### List completed scans [GET]
+ Response 200 (application/json)

        ["important_scan","less_important_scan"]

### Download completed scan [GET]
+ Response 200 (image/<type>)

        The file as a binary blob.
